#pragma once
#include "SFML/Graphics.hpp"

namespace Keyboard {
	
// Keys Dragonfly recognizes.
enum Key {
	UNDEFINED_KEY = -1,
	SPACE = sf::Keyboard::Space,
	RETURN = sf::Keyboard::Return,
	ESCAPE = sf::Keyboard::Escape,
	TAB = sf::Keyboard::Tab,
	LEFTARROW = sf::Keyboard::Left,
	RIGHTARROW = sf::Keyboard::Right,
	UPARROW = sf::Keyboard::Up,
	DOWNARROW = sf::Keyboard::Down,
	PAUSE = sf::Keyboard::Pause,
	MINUS = sf::Keyboard::Subtract,
	PLUS = sf::Keyboard::Add,
	TILDE = sf::Keyboard::Tilde,
	PERIOD = sf::Keyboard::Period,
	COMMA = sf::Keyboard::Comma,
	SLASH = sf::Keyboard::Slash,
	LEFTCONTROL = sf::Keyboard::LControl,
	RIGHTCONTROL = sf::Keyboard::RControl,
	LEFTSHIFT = sf::Keyboard::LShift,
	RIGHTSHIFT = sf::Keyboard::RShift,
	F1 = sf::Keyboard::F1,
	F2 = sf::Keyboard::F2,
	F3 = sf::Keyboard::F3,
	F4 = sf::Keyboard::F4,
	F5 = sf::Keyboard::F5,
	F6 = sf::Keyboard::F6,
	F7 = sf::Keyboard::F7,
	F8 = sf::Keyboard::F8,
	F9 = sf::Keyboard::F9,
	F10 = sf::Keyboard::F10,
	F11 = sf::Keyboard::F11,
	F12 = sf::Keyboard::F12,
	A = sf::Keyboard::A,
	B = sf::Keyboard::B,
	C = sf::Keyboard::C,
	D = sf::Keyboard::D,
	E = sf::Keyboard::E,
	F = sf::Keyboard::F,
	G = sf::Keyboard::G,
	H = sf::Keyboard::H,
	I = sf::Keyboard::I,
	J = sf::Keyboard::J,
	K = sf::Keyboard::K,
	L = sf::Keyboard::L,
	M = sf::Keyboard::M,
	N = sf::Keyboard::N,
	O = sf::Keyboard::O,
	P = sf::Keyboard::P,
	Q = sf::Keyboard::Q,
	R = sf::Keyboard::R,
	S = sf::Keyboard::S,
	T = sf::Keyboard::T,
	U = sf::Keyboard::U,
	V = sf::Keyboard::V,
	W = sf::Keyboard::W,
	X = sf::Keyboard::X,
	Y = sf::Keyboard::Y,
	Z = sf::Keyboard::Z,
	NUM1 = sf::Keyboard::Num1,
	NUM2 = sf::Keyboard::Num2,
	NUM3 = sf::Keyboard::Num3,
	NUM4 = sf::Keyboard::Num4,
	NUM5 = sf::Keyboard::Num5,
	NUM6 = sf::Keyboard::Num6,
	NUM7 = sf::Keyboard::Num7,
	NUM8 = sf::Keyboard::Num8,
	NUM9 = sf::Keyboard::Num9,
	NUM0 = sf::Keyboard::Num0
};

}